### PR TITLE
Application

### PR DESCRIPTION
**Pull request by AliRezaTaheriyoun**
Pull request for the application branch

### CODE REVIEW

**Comment by alleneross** [comment]
@AliRezaTaheriyoun can you describe a bit in the overview or a comment what is actually in this pull request?

**Comment by alleneross** [comment]
Also I was talking with @grahnavard and I think we want to make a standard folder directory for the examples. In there should probably just be something that looks like this:
```
examples/
--- Breastmilk/
      --- breastmilk.ipynb
      --- output/
            --- breastmilk_models.pkl
      --- data/
            --- infant_metadata.csv
            --- infant_metabote.tsv
            --- stool_metadata.csv
```
Please make sure to only push exactly what is needed to reproduce the output!

**Comment by AliRezaTaheriyoun** [comment]
@alleneross I have changed the appearance of the "Read me.md" markdown file and have fixed the links in it. 
In the Application branch I have provided '.ipynb' notebook files concerning the application of _waveome_ onto:
1. Breastmilk study gut microbiome
2. Breastmilk study metabolites,
3. A simple bivariate CD4 count for HIV cohorts.
All the ipython notebook  files provide the step-by-step descriptions from definition of the variables towards the kernel search procedure. 
Since sometimes the kernel search requires a considerable time for running, I have also add some lines to show how users can save the output of `GPSearch` and use it offline. However, I have not followed the standard folder structures yet. So, if it is advisable let me first make the folder structures and then I will push the changes into Application branch and will make a new PULL request.

**Comment by alleneross** [comment]
I believe you should restructure the directory as stated above for the breastmilk and CD4 folders and then push your changes to the remote repository to the same Applications branch and it should automatically update this pull request. You shouldn't need to make a new request.

**Comment by AliRezaTaheriyoun** [comment]
Thank you. I will do so tonight if I may.

**Review by alleneross — APPROVED** [review]
Looks good. We might need to clean up some of the folders more in the future, but for now this should be fine. Also in the future let's try to have smaller branches so it is easier for us to review the work.

**Pull request merged**
